// Transcripts for YouTube videos. The watch page's HTML lists its caption
// tracks; one of them is fetched as JSON and turned into timestamped text.

export function youtubeVideoId(url) {
  try {
    const u = new URL(url);
    const host = u.hostname.replace(/^(www|m)\./, "");
    if (host === "youtu.be") return u.pathname.slice(1).split("/")[0] || null;
    if (host !== "youtube.com" && host !== "youtube-nocookie.com") return null;
    if (u.pathname === "/watch") return u.searchParams.get("v");
    const m = u.pathname.match(/^\/(?:shorts|embed|live)\/([\w-]{6,})/);
    return m ? m[1] : null;
  } catch {
    return null;
  }
}

// Finds the JSON array that follows `"captionTracks":` by matching brackets,
// since the array can contain nested objects.
function captionTracksFrom(html) {
  const start = html.indexOf('"captionTracks":');
  if (start < 0) return [];
  let i = html.indexOf("[", start);
  if (i < 0) return [];
  let depth = 0;
  let inString = false;
  for (let j = i; j < html.length; j++) {
    const ch = html[j];
    if (inString) {
      if (ch === "\\") j++;
      else if (ch === '"') inString = false;
    } else if (ch === '"') inString = true;
    else if (ch === "[") depth++;
    else if (ch === "]" && --depth === 0) {
      try {
        return JSON.parse(html.slice(i, j + 1));
      } catch {
        return [];
      }
    }
  }
  return [];
}

function pickTrack(tracks, preferredLang) {
  const lang = (preferredLang || "en").slice(0, 2).toLowerCase();
  const score = (t) =>
    (t.languageCode?.toLowerCase().startsWith(lang) ? 2 : 0) + (t.kind === "asr" ? 0 : 1);
  return [...tracks].filter((t) => t.baseUrl).sort((a, b) => score(b) - score(a))[0] ?? null;
}

function formatTime(seconds) {
  const s = Math.max(0, Math.round(seconds));
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const sec = s % 60;
  return h ? `${h}:${String(m).padStart(2, "0")}:${String(sec).padStart(2, "0")}` : `${m}:${String(sec).padStart(2, "0")}`;
}

/**
 * Returns { text, language, duration, segments } for the video, or null
 * when the page has no captions. text is paragraphs of roughly 20 seconds,
 * each starting with a [m:ss] timestamp.
 */
export async function fetchTranscript(url, { preferredLang } = {}) {
  const id = youtubeVideoId(url);
  if (!id) return null;
  const page = await fetch(`https://www.youtube.com/watch?v=${encodeURIComponent(id)}&hl=en`, { credentials: "include" });
  if (!page.ok) throw new Error(`YouTube returned HTTP ${page.status}`);
  const html = await page.text();
  const track = pickTrack(captionTracksFrom(html), preferredLang);
  if (!track) return null;

  const trackUrl = new URL(track.baseUrl);
  trackUrl.searchParams.set("fmt", "json3");
  const response = await fetch(trackUrl, { credentials: "include" });
  if (!response.ok) throw new Error(`Transcript request failed (HTTP ${response.status})`);
  const data = await response.json();
  const segments = [];
  for (const event of data.events ?? []) {
    const text = (event.segs ?? []).map((s) => s.utf8 ?? "").join("").replace(/\s+/g, " ").trim();
    if (text) segments.push({ start: (event.tStartMs ?? 0) / 1000, text });
  }
  if (!segments.length) return null;

  const paragraphs = [];
  let current = null;
  for (const seg of segments) {
    if (!current || seg.start - current.start >= 20) {
      current = { start: seg.start, parts: [] };
      paragraphs.push(current);
    }
    current.parts.push(seg.text);
  }
  const titleMatch = html.match(/<meta name="title" content="([^"]*)"/);
  return {
    videoId: id,
    title: titleMatch ? decodeEntities(titleMatch[1]) : null,
    language: track.languageCode ?? null,
    autoGenerated: track.kind === "asr",
    duration: segments.at(-1).start,
    segments,
    text: paragraphs.map((p) => `[${formatTime(p.start)}] ${p.parts.join(" ")}`).join("\n\n"),
  };
}

function decodeEntities(text) {
  const el = document.createElement("textarea");
  el.innerHTML = text;
  return el.value;
}

/** Seconds for a [h:mm:ss] or [m:ss] timestamp string. */
export function timestampSeconds(stamp) {
  const parts = stamp.split(":").map(Number);
  if (parts.some(Number.isNaN)) return null;
  return parts.reduce((total, part) => total * 60 + part, 0);
}
